import { z } from 'zod';

export const MetadataSchema = z.object({
	project: z.string().min(1),
	source: z.string().min(1),
	tags: z.array(z.string()).default([]),
	createdAt: z.string().datetime().optional(), // usually server-side autogenerated
	expiresAt: z.string().datetime().optional(),
	importance: z.number().min(0).max(1).default(0.5),
	chunkIndex: z.number().int().min(0).optional(),
	chunkTotal: z.number().int().min(1).optional(),
	topic: z.string().optional(),
	documentId: z.string().uuid().optional(),
	inputType: z.enum(['text', 'image', 'audio', 'pdf', 'mixed']).optional(),
	extra: z.record(z.any()).default({}),
});

export type MemoryMetadata = z.infer<typeof MetadataSchema>;

export function validateMetadata(data: any): MemoryMetadata {
	return MetadataSchema.parse(data);
}
